### ISSUE TITLE
The links for GhostFaceNetV2 models are broken

### ISSUE THREAD

**Issue by ak4ever87** [HamadYA/GhostFaceNets#1]
Great repo,
can you please provide the models for GhostFaceNetV2

**Comment by HamadYA** [comment]
> Great repo, can you please provide the models for GhostFaceNetV2

Hi,

I am still adding the models and modifying the repository.
I will add everything soon.

Sorry for inconvenience caused.

**Comment by Richienb** [comment]
Friendly bump :)
@HamadYA

**Comment by HamadYA** [comment]
> Friendly bump :) @HamadYA


Hi,

I encountered some difficulties in reproducing certain results due to a hard disk corruption. As a result, I lost the GhostFaceNetsV2 experiments and the GhostFaceNetsV1 experiments with different modifications. I apologize for any inconvenience caused. I will work on recovering these experiments once I have completed my current workload. Thank you for your understanding.
