### ISSUE TITLE
Can you please share GhostFaceNetV2 weights? 

### ISSUE THREAD

**Issue by martinenkoEduard** [HamadYA/GhostFaceNets#22]
Can you please share GhostFaceNetV2 weights? 
And how do I use them for inference?

**Comment by HamadYA** [comment]
> Can you please share GhostFaceNetV2 weights? And how do I use them for inference?

The GhostFaceNetsV2 weights will not be available for a period of time due to the lack of computational resources I currently have. However, you can always train it from scratch using the training details in the paper.

For inference:
Please refer to https://github.com/HamadYA/GhostFaceNets/issues/12#issuecomment-1567254521

Let me know if you need further assistance
